### ISSUE TITLE
Strange behaviour when team is full

### ISSUE THREAD

**Issue by andreped** [andreped/super-ml-pets#14]
When deploying the AI against real people, I observed that it tends to sell an item (maybe always the first?). When this happens, it seems to be able to move the first item (which has been sold) to another place, which of course is not possible. When this happens, the AI just starts doing strange things. Perhaps there is something wrong with the engine when animals are sold? Or the machine vision system at fails?  Perhaps a longer pause is needed between each action?

**Comment by andreped** [comment]
This might be related to this issue: https://github.com/andreped/super-ml-pets/issues/15

**Comment by GoldExplosion** [comment]
I think the Pet is not sold but pilled(you probably didn't catch it since it was happening very fast). There is an issue with pilling a pet in this framework probably because of the following piece of code https://github.com/andreped/super-ml-pets/blob/a5f7be6e134c2680b56cdd94772984469003bf75/src/agent.py#L74
It is not a problem with sapai itself as pilling works properly in the engine's tests. Pilling a Pet adds -1000 to the Pet's health. The above code keep the AI player from dying but also breaks the sapai engine's pilling mechanism and allows Pet with -1000 health to continue playing.
We need to know if the AI won or lost against real opponent so that we can avoid using altering the number of lives remaining.

**Comment by andreped** [comment]
Makes sense. I think it is very smart of us to get the deployment stuff working properly, before doing a lot more on the RL-aspect. I believe the model I have trained is actually decent, it just fails to win more than 2-3 games, as bugs seem to occur when the team is full (or after shuffling a lot). Not really sure what the main reason is.

Would be great if you could take a look at it.

**Comment by GoldExplosion** [comment]
Yes, will do. Can you describe the bugs that occur when team is full or after shuffling a lot (other than the pilling issue where it assumes a dead Pet to be alive) if there are any?

**Comment by andreped** [comment]
I think it is easier if you just test the model during deployment. You should see it quite early on.

I would recommend having two monitors, one displaying the game where the AI is playing, and the other showing the terminal.

**Comment by andreped** [comment]
The issue I observed was not related to the team being full, but rather to how teams were reordered. This has now been fixed in fa8516ba40ee2b0c81ae92b513fdc6f3b973bea6.

Could be that there is a strange behaviour if an animal is sold, but I have not observed it yet. Could create a separate issue if the sold event is broken.
