### ISSUE TITLE
Multiple screens

### ISSUE THREAD

**Issue by jpdefrutos** [andreped/super-ml-pets#35]
The process fails to detect the correct monitor where the game is.
Got an error from the ```find_the_animals``` routine.

**Comment by andreped** [comment]
Yeah, thats true. I have started adding support on it, but didnt have the time to finish it.

The current solution is also only made for a single screen resolution, which is quite silly.

Will hopefully make a fix this weekend.

Did you manage to test deployment on a machine with a single screen btw?

**Comment by andreped** [comment]
It appears that `pyautogui` just does not support multiple displays (see [here](https://pyautogui.readthedocs.io/en/latest/#faq-frequently-asked-questions)).

Hence, this is outside the scope of this project. If they ever were to add a fix, we could integrate it, but until then, this issue is not much we can do about.

Closing for now.
