### ISSUE TITLE
virtualenv help

### ISSUE THREAD

**Issue by Gyrnw** [andreped/super-ml-pets#74]
**Describe the bug**
Virtualenv not being recognized, despite virtualenv being installed

**To Reproduce**
PS C:\Users\HP\super-ml-pets> virtualenv -ppython3 venv --clear
virtualenv : The term 'virtualenv' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ virtualenv -ppython3 venv --clear
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (virtualenv:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Expected behavior**
virtualenv to be recognized

**Desktop (please complete the following information):**
 - OS: Win 11
 - Python: 3.11.6

**Comment by andreped** [comment]
Hello, @Gyrnw!

You can try by first installing `virtualenv` and trying again through the command:
```
py -m pip install virtualenv
virtualenv -ppython3 venv --clear
```

I used `py` here, as I assumed you had `py` on Windows, but if that is not available, it might be that Python is available through `python` or `python3`, if at all installed.

Alternatively, you can use `venv` instead of `virtualenv`, which should be bundled with Python:
```
py -m venv venv/
```

For both, then you can activate the virtual environment using (example for Windows):
```
./venv/Scripts/activate.ps1
```

**Comment by Gyrnw** [comment]
Thank you, it is now resolved
